FROM ubuntu:latest
RUN apt-get update && apt-get install –quiet –assume-yes python-pip unzip wget
RUN pip install -U pip
robotframework
robotframework-appiumlibrary==1.5.0.1
robotframework-browsermobproxylibrary
robotframework-databaselibrary
robotframework-imaplibrary
robotframework-requests
robotframework-seleniumlibrary
robotframeworklexer==1.1
cx-Oracle
browsermob-proxy
Appium-Python-Client==0.31
view raw
CMD["/bin/sh","-c", "robot -d output -o output.xml test.robot"]
